language: node_js
node_js:
  - 10

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE devtools;" -U postgres
  - psql -c "CREATE USER docker WITH PASSWORD 'docker';" -U postgres

script:
  - npm install
  - npm ci
  - npm run tests

notifications:
  email: false
